### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-cli#28]
If you're trying to log in when graphql api is down or unreachable you will get `Invalid credentials, please try again!` error no matter what. It's rather confusing. 

To reproduce: try logging in to some non-existent graphql endpoint. `c0d3 login --url foobar.com`.

**Comment by ggwadera** [comment]
Some info for whoever is going to do this.

The login command is handled here
https://github.com/garageScript/c0d3-cli/blob/bc0b9226f5eea083a31beb287aa94759041282a1/src/commands/login.ts#L8-L18

The graphql request is sent here
https://github.com/garageScript/c0d3-cli/blob/bc0b9226f5eea083a31beb287aa94759041282a1/src/util/credentials.ts#L28-L35

There's a try/catch block that just prints the same message for whatever error that was raised.
https://github.com/garageScript/c0d3-cli/blob/bc0b9226f5eea083a31beb287aa94759041282a1/src/messages.ts#L22-L24

Would probably need to check the response status or error message and print something like `Server unreachable. Try again later.` for this case.
