### ISSUE TITLE
Add testing before submission

### ISSUE THREAD

**Issue by SlyBouhafs** [garageScript/c0d3-cli#41]
The idea is to add add testing to the submitting process, so that once a user selects the challenge to be submitted, it will pass through the tests before getting sent to c0d3.

This will make the review process a bit easier, mentors won't have to worry if the code works or not and can focus on other aspects of the review.

I will add more information once i start working on the issue.

**Comment by flacial** [comment]
I think it can be done using [husky](https://typicode.github.io/husky/#/) like https://github.com/garageScript/c0d3-app/blob/master/.husky/pre-push

**Comment by SlyBouhafs** [comment]
> I think it can be done using [husky](https://typicode.github.io/husky/#/) like https://github.com/garageScript/c0d3-app/blob/master/.husky/pre-push but for c0d3 submit

That's a good proposition but I think husky is geared more towards git hooks, when a students submits a solution, the cli mostly takes a diff and sends it back to the server, there's no git action to attach it to (commit/push), so i think just calling `yarn test` before submitting and exiting once it fails a test will do the job.

**Comment by flacial** [comment]
@SlyBouhafs Good solution! Let's explore it!
