### ISSUE TITLE
`logout` cli not working

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-cli#7]
When you type `c0d3 logout`, you get the following, which makes people feel like they are still logged in.

<img width="614" alt="Screen Shot 2020-10-28 at 7 25 51 AM" src="https://user-images.githubusercontent.com/686933/97372767-a1366600-1871-11eb-9488-c7b0a45fa5b0.png">

For the time being, logout by typing `rm -rf ~/.c0d3`

**Comment by SlyBouhafs** [comment]
@songz So, i tried to reproduce the bug and found out that the `logout` function is working as intended, it is removing the `~/.c0d3` folder correctly, the only issue i encountered was that the returned message was wrong, i fixed it and sent a PR!
